### ISSUE TITLE
Hard Normals

### ISSUE THREAD

**Issue by mittpat** [gregeryb/DAEBlend#9]
Hi

I really appreciate your exporter for the Collada 1.5 features. However, it doesn't seem to support hard normals (simple unit cube for example), whereas Better Collada Exporter does.

Could you help me fix that?

At li 455
normals = [v.normal.copy().freeze() for v in mesh.vertices.values()]

I'm guessing that its here that we should look at loops/edges/faces to identify hard/soft normals. I believe that if I just blindly change the way the normal array is built I'll break the relation with positions/vertices, I'm not really sure what the best approach would be.

[cube15.dae](https://github.com/gregeryb/DAEBlend/files/2413590/cube15.txt)

Any ideas?

Thanks!

**Comment by mittpat** [comment]
I've implemented a workaround in my fork, which is ok for me but totally overkill in objective terms.
Basically, I first export to DAE using the built-in bpy DAE exporter, then using your exporter and then splice both xml together... I won't loose any sleep over it, but I might try to do something more efficient later in the week.

https://github.com/mittpat/DAEBlend/commit/305c1e5c8d9739255cb9a5311a7eed16db6e0a58

**Comment by gregdavisd** [comment]
A hard normal edge requires duplicating the position with a separate normal. In blender there is the auto smooth modifier which breaks edges based on a critical angle. I don't know if there is anything like 3ds max smoothing groups in blender. The exporter works with the vertex data it's  given instead of generating geometry. I'll investigate when I get a chance  later tonight if it's a configuration issue or see what's going on.

**Comment by gregdavisd** [comment]
Here's a test file with two cubes: 


[test file](https://github.com/gregeryb/DAEBlend/blob/master/testing/soft%20and%20hard%20lighting%20cube.blend)


![soft and hard blender](https://user-images.githubusercontent.com/2530447/46005837-8379fe00-c0f9-11e8-84dc-8962afff428a.png)

Here's the exported DAE file rendered with FBX review


![soft and hard review](https://user-images.githubusercontent.com/2530447/46005907-a4425380-c0f9-11e8-878c-8d881816f850.png)


The cubes appear with correct lighting from the DAE file. 


To get a flat lighting the edges need to be split with the "split modifier" or "split edge" command. Here is a cube corner with a single smoothing normal:



![smooth cube](https://user-images.githubusercontent.com/2530447/46006634-51699b80-c0fb-11e8-93c1-0e45d1a5b44a.png)


And here's the cube corner showing flat shading normals from splitting edges:


![flat cube](https://user-images.githubusercontent.com/2530447/46006682-72ca8780-c0fb-11e8-81f0-cb3d27e8d471.png)


So it depends what you mean by a flat shaded cube. Using the "Shading: Smooth" button will have no effect on the export if all that button does in modify Blender's pixel shader without making changes to the geometry.

Regards,
Greg.

**Comment by mittpat** [comment]
Hi, thanks for the reply.

Yes custom split normals appear to work properly with DAEBlend,

However, using Blender 2.79 on Ubuntu, creating two cubes and smoothing one with the uvshading buttons with this visual result:
![uvshading](https://user-images.githubusercontent.com/42945017/46011431-cb663a00-c093-11e8-8801-f3bcf1f08c8c.png)

Once exported with the builtin exporter:
[two_cubes-builtin.dae](https://github.com/gregeryb/DAEBlend/files/2414988/two_cubes-builtin.txt)

Once exported with DAEBlend:
[two_cubes-DAEblend.dae](https://github.com/gregeryb/DAEBlend/files/2414987/two_cubes-DAEblend.txt)

As you can see, all the DAEBlend normals, for both cubes are at 45 degrees (-0.5773 -0.5773 -0.5773)
While the builtin exporter (OpenCollada) has the smooth cube normals at (-0.5773 -0.5773 -0.5773) but the hard cube normals at (1 0 0).

blend file:
[two_cubes.blend](https://github.com/gregeryb/DAEBlend/files/2414996/two_cubes.blend.txt)

Thanks for putting your exporter on the web, it'a great help with Collada 1.5.0,

Pat

**Comment by mittpat** [comment]
Also, this post on the web may give a hint:

https://blender.stackexchange.com/questions/71356/vertex-normals-different-from-loop-normals

Quote:

    data.calc_tessface();
    for f in data.tessfaces:  # indices
        polygon = data.polygons[f.index] #Load Polygon

        for vert in range(len(f.vertices)):
            norm = data.vertices[f.vertices[vert]].normal
            norm1 = data.loops[polygon.vertices[vert]].normal
            print(norm, norm1)

<Vector (-0.5773, 0.5773, -0.5773)> <Vector (-1.0000, 0.0000, 0.0000)>
<Vector (-0.5773, -0.5773, -0.5773)> <Vector (-1.0000, 0.0000, 0.0000)>
<Vector (-0.5773, -0.5773, 0.5773)> <Vector (-1.0000, 0.0000, 0.0000)>
...

**Comment by gregdavisd** [comment]
The autosmooth option wasn't working so I fixed that. For a cube mesh, turn on the autosmooth checkbox under data tab and set angle < 90 degrees. That will now export sharp edges based on the angle limit. This exporter doesn't use the 'calc_normals()' api call, that will have to be done manually using the menu 'normals->recalculate outside/inside'.

**Comment by mittpat** [comment]
It is now working as you describe.

Thanks!
